### ISSUE TITLE
DISALLOW_COPY_AND_ASSIGN

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#207] opened 2014-04-09 06:25 UTC
It looks like the new macro breaks some parts of the Python wrapper. I think this needs to be fixed in the CoolProp.pyx:

```
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for Ada/C/ObjC but not for C++ [enabled by default]
../../CoolProp/CPState.h: In function ‘PyObject* __pyx_fuse_0__pyx_f_8CoolProp_8CoolProp_5State_set_Fluid(__pyx_obj_8CoolProp_8CoolProp_State*, PyObject*, int)’:
../../CoolProp/CPState.h:167:2: error: ‘void CoolPropStateClassSI::operator=(const CoolPropStateClassSI&)’ is private
build/temp.linux-i686-2.7/pyrex/CoolProp/CoolProp.cpp:17125:59: error: within this context
../../CoolProp/CPState.h:167:2: error: ‘void CoolPropStateClassSI::operator=(const CoolPropStateClassSI&)’ is private
build/temp.linux-i686-2.7/pyrex/CoolProp/CoolProp.cpp:17130:25: error: within this context
../../CoolProp/CPState.h: In function ‘PyObject* __pyx_fuse_1__pyx_f_8CoolProp_8CoolProp_5State_set_Fluid(__pyx_obj_8CoolProp_8CoolProp_State*, PyObject*, int)’:
../../CoolProp/CPState.h:167:2: error: ‘void CoolPropStateClassSI::operator=(const CoolPropStateClassSI&)’ is private
build/temp.linux-i686-2.7/pyrex/CoolProp/CoolProp.cpp:17382:59: error: within this context
../../CoolProp/CPState.h:167:2: error: ‘void CoolPropStateClassSI::operator=(const CoolPropStateClassSI&)’ is private
build/temp.linux-i686-2.7/pyrex/CoolProp/CoolProp.cpp:17387:25: error: within this context
```

I don't have time now, but maybe someone else can fix it ;-)

**Comment by ibell** [comment] 2014-04-09 06:41
I can remove the do not copy macro, but it helps in terms of fixing some
weird copy/assignment bugs.  I can take a look

**Comment by ibell** [comment] 2014-04-09 08:44
Looks like python wants to be able to assign to the class.  Let's remove
the macro entirely I guess.

**Comment by ibell** [comment] 2014-04-09 08:53
The problem is copying of the pointers - its a big pain.

**Comment by ibell** [comment] 2014-05-05 22:03
This has been undone - sorry for the noise.

**Closed as completed by ibell** 2014-05-05 22:03 UTC
