### ISSUE TITLE
Compiling on a Mac

### ISSUE THREAD

**Issue by vancesteven** [ibell/coolprop#229] opened 2014-07-21 01:09 UTC
Hi, I'm a fan of REFPROP but would prefer to see something useable on multiple platforms.  Coolprop looks like it lives up to its name in that sense.  Sadly, I'm having trouble compiling it.  I suspect it's something to do with the fact that I have been trying to learn python using Enthought Canopy, which screws with the directory structure of python.  I'm working with coolprop-master.  Here is the error I get when I run MakeDistro.py after changing the PYTHONVERSIONS to have my path: $HOME/Library/Enthought/Canopy_64bit/User/bin/python:

from: can't read /var/mail/**future**
./MakeDistro.py: line 2: import: command not found
./MakeDistro.py: line 11: ]: command not found
./MakeDistro.py: line 13: syntax error near unexpected token `('
./MakeDistro.py: line 13:`if not os.path.exists('_deps'):'

when I run setup.py under wrappers/Python, I get this error:
raceback (most recent call last):
  File "setup.py", line 34, in <module>
    if cmdline and ''.join(cmdline).find('pycompletionserver.py') > 0:
TypeError

I also tried getting it through easy_install but I get this:
Processing CoolProp-4.2.3.zip
Writing /tmp/easy_install-8fP2N4/CoolProp-4.2.3/setup.cfg
Running CoolProp-4.2.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-8fP2N4/CoolProp-4.2.3/egg-dist-tmp-nqpkkn
Traceback (most recent call last):
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/bin/easy_install", line 10, in <module>
    sys.exit(main())
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1978, in main
    with_ei_usage(lambda:
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1959, in with_ei_usage
    return f()
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1982, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 360, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 634, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 829, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1109, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1095, in run_setup
    run_setup(setup_script, args)
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/sandbox.py", line 33, in run_setup
    lambda: execfile(
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/sandbox.py", line 81, in run
    return func()
  File "/Users/svance/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/setuptools/sandbox.py", line 35, in <lambda>
    {'**file**':setup_script, '**name**':'**main**'}
  File "setup.py", line 34, in <module>

Thanks for your help,
Steve

**Comment by ibell** [comment] 2014-07-21 02:21
There's no need to mess with the MakeDistro.py - the best bet is to use the
setup.py file in wrappers/Python.  You can just do a python setup.py
install in the wrappers/Python folder, which should "just work".  Also, I
recommend Anaconda over enthought.  Anaconda/Miniconda seems to becoming
the standard nowadays.

Good luck, and feel free to chime in with further progress/issues.

**Comment by vancesteven** [comment] 2014-07-21 05:21
Ian,

Thanks for the quick response!

Here's the error I get.  It's odd, because I can 'import setuptools' while
running python interactively

from: can't read /var/mail/**future**
./setup.py: line 3: try:: command not found
./setup.py: line 4: import: command not found
./setup.py: line 5: except: command not found
./setup.py: line 6: pass: command not found
./setup.py: line 8: try:: command not found
./setup.py: line 9: import: command not found
./setup.py: line 10: except: command not found
./setup.py: line 11: syntax error near unexpected token `('
./setup.py: line 11:`    raise ImportError("Cython not found")'

Steve

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Comment by vancesteven** [comment] 2014-07-21 07:29
Thanks for the anaconda tip too.  I have the same problem with there.
Granted, I'm using the python 3 version....

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Comment by ibell** [comment] 2014-07-21 12:05
You need Cython before you can compile CoolProp.  You can do

pip install Cython

from the command line.  You are getting differently formatted tracebacks,
but I guess that is something to do with Enthought.

**Comment by vancesteven** [comment] 2014-07-21 12:55
That's the odd thing.  Cython was installed under Enthought, and is also
installed under anaconda.

Python svance$ cython --version
Cython version 0.20.1

from: can't read /var/mail/**future**
./setup.py: line 3: try:: command not found
./setup.py: line 4: import: command not found
./setup.py: line 5: except: command not found
./setup.py: line 6: pass: command not found
./setup.py: line 8: try:: command not found
./setup.py: line 9: import: command not found
./setup.py: line 10: except: command not found
./setup.py: line 11: syntax error near unexpected token `('
./setup.py: line 11:`    raise ImportError("Cython not found")'

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Comment by ibell** [comment] 2014-07-21 20:09
Do you get anything else on the command line when you try to build?  Can
you copy-paste the full console output?

**Comment by vancesteven** [comment] 2014-07-22 01:26
It's different if I run python setup.py install:

LMC-035525:Python svance$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    if cmdline and ''.join(cmdline).find('pycompletionserver.py') > 0:
TypeError: can only join an iterable

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Comment by ibell** [comment] 2014-07-22 02:29
Try removing psutils, or alternatively, remove this block:
https://github.com/ibell/coolprop/blob/master/wrappers/Python/setup.py#L30-L39
- they changed the API for psutils it seems.  Or it just doesn't work with
  py3.x

**Comment by vancesteven** [comment] 2014-07-22 02:53
Commenting out the highlighted passage seems to result in progress, and
results in a clang error.

python setup.py install
git version 1.8.3.4 (Apple Git-47)
git was found
fatal: Not a git repository (or any of the parent directories): .git
tried to update git revision, but it failed for some reason (building from
zip file?)
running install
running bdist_egg
running egg_info
creating CoolProp.egg-info
writing dependency_links to CoolProp.egg-info/dependency_links.txt
writing CoolProp.egg-info/PKG-INFO
writing top-level names to CoolProp.egg-info/top_level.txt
writing manifest file 'CoolProp.egg-info/SOURCES.txt'
reading manifest file 'CoolProp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '_._' under directory 'CoolPropSource'
warning: no files found matching 'version.txt'
writing manifest file 'CoolProp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.5-x86_64-3.4
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp
copying CoolProp/**init**.py -> build/lib.macosx-10.5-x86_64-3.4/CoolProp
copying CoolProp/HumidAirProp.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp
copying CoolProp/State.py -> build/lib.macosx-10.5-x86_64-3.4/CoolProp
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/**init**.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/Common.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/Plots.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/PsychChart.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/PsychScript.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/SimpleCycles.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
copying CoolProp/Plots/Tests.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/Plots
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/**init**.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/runner.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_consistency.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_CoolPropState.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_HAProps.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_param_getters.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_plots.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_Props.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_Props1.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_PropsSI.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_Saturation.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
copying CoolProp/tests/test_Units_CPState.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp/GUI
copying CoolProp/GUI/**init**.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/GUI
copying CoolProp/GUI/CoolPropGUI.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/GUI
copying CoolProp/GUI/PsychScript.py ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/GUI
copying CoolProp/State.pxd -> build/lib.macosx-10.5-x86_64-3.4/CoolProp
copying CoolProp/CoolProp.pxd -> build/lib.macosx-10.5-x86_64-3.4/CoolProp
copying CoolProp/param_constants_header.pxd ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/AllFluids.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Brine.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CoolProp.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CoolPropDLL.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CoolPropTools.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CPExceptions.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CPState.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CriticalSplineConstants.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/CriticalSplineConstants_T.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Deprecated.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/FluidClass.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/gitrevision.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/GlobalConstants.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Helmholtz.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/HumidAirProp.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Ice.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/IncompBase.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/IncompLiquid.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/IncompSolution.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/JSON_CAS.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/JSON_code.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/MatrixMath.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/mixture_excess_JSON.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/mixture_reducing_JSON.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Mixtures.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/MPLPlot.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/rapidjson_CoolProp.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/REFPROP.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/REFPROP_lib.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Solvers.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Spline.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Tests.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/TTSE.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/Units.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
copying CoolProp/include/version.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/document.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/filestream.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/prettywriter.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/rapidjson.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/reader.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/stringbuffer.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
copying CoolProp/include/rapidjson/writer.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson
creating
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson/internal
copying CoolProp/include/rapidjson/internal/pow10.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson/internal
copying CoolProp/include/rapidjson/internal/stack.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson/internal
copying CoolProp/include/rapidjson/internal/strfunc.h ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/include/rapidjson/internal
copying CoolProp/CoolPropBibTeXLibrary.bib ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp
creating build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests/baseline_images
creating
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests/baseline_images/test_plots
copying
CoolProp/tests/baseline_images/test_plots/Graph_annotations_tests.png ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests/baseline_images/test_plots
copying CoolProp/tests/baseline_images/test_plots/Isolines_plot_tests.png
->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests/baseline_images/test_plots
copying CoolProp/tests/baseline_images/test_plots/Ph_plot_tests.png ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests/baseline_images/test_plots
copying CoolProp/tests/baseline_images/test_plots/Ts_plot_tests.png ->
build/lib.macosx-10.5-x86_64-3.4/CoolProp/tests/baseline_images/test_plots
running build_ext
cythoning CoolProp/CoolProp.pyx to
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp
creating build/temp.macosx-10.5-x86_64-3.4
creating build/temp.macosx-10.5-x86_64-3.4/pyrex
creating build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp
building 'CoolProp.CoolProp' extension
creating build/temp.macosx-10.5-x86_64-3.4/build
creating build/temp.macosx-10.5-x86_64-3.4/build/temp.macosx-10.5-x86_64-3.4
creating
build/temp.macosx-10.5-x86_64-3.4/build/temp.macosx-10.5-x86_64-3.4/pyrex
creating
build/temp.macosx-10.5-x86_64-3.4/build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp
/usr/bin/clang -fno-strict-aliasing -Werror=declaration-after-statement
-DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
-I/Users/svance/anaconda/include -arch x86_64 -I../../CoolProp
-I/Users/svance/anaconda/include/python3.4m
-I/Users/svance/anaconda/include/python3.4m -c
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp -o
build/temp.macosx-10.5-x86_64-3.4/build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.o
In file included from
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:349:
../../CoolProp/CPState.h:246:2: warning: control may reach end of non-void
      function [-Wreturn-type]
        };
        ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25556:26:
error:
      expected the class name after '~' to name a destructor
  p->Fluid.std::string::~string();
                         ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25557:26:
error:
      expected the class name after '~' to name a destructor
  p->phase.std::string::~string();
                         ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25798:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "CoolPropStateClass",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25799:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "CoolPropStateClassSI",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25800:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "State",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25801:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "__pyx_opt_args_8CoolProp_8CoolProp_5State_get_Tsat",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25802:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "__pyx_opt_args_8CoolProp_8CoolProp_Props",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25803:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "__pyx_opt_args_8CoolProp_8CoolProp_PropsSI",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25804:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "__pyx_opt_args_8CoolProp_8CoolProp_fromSI",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25805:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "__pyx_opt_args_8CoolProp_8CoolProp_toSI",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25806:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "params",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25807:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "phase",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25808:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "string",
  ^
build/temp.macosx-10.5-x86_64-3.4/pyrex/CoolProp/CoolProp.cpp:25809:3:
warning:
      conversion from string literal to 'char *' is deprecated
      [-Wdeprecated-writable-strings]
  "string_like",
  ^
13 warnings and 2 errors generated.
error: command '/usr/bin/clang' failed with exit status 1

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Comment by ibell** [comment] 2014-07-22 02:55
Ah the problem is py3.4 - there is a problem in Cython with py3.4 that I
haven't been able to resolve.  For now its py 3.3, 3.2 or 2.7.  Sorry.

**Comment by vancesteven** [comment] 2014-07-22 15:57
Okay, I got it working in 2.7 --> conda create py2k py=2 is nice

After making sure I can run query the version (4.2.3) and get properties of
fluids, I tried plotting something from some of the examples.  Here is the
error I keep getting in ipython notepad.

In [43]:

ts_plot = PropsPlot('R290', 'Ts')

ts_plot.show()

---------------------------------------------------------------------------TypeError
                                Traceback (most recent call
last)<ipython-input-43-dae5f0cbc426> in <module>()      1 ts_plot =
PropsPlot('R290', 'Ts')----> 2 ts_plot.show()
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Common.pyc
in show(self)    296     297     def show(self):--> 298
self._draw_graph()    299         matplotlib.pyplot.show()
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Plots.pyc
in _draw_graph(self)    500     501     def _draw_graph(self):--> 502
       self.__draw_region_lines()    503
self._plot_default_annotations()    504
self.scale_plot(plot_units=self.plot_units)
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Plots.pyc
in __draw_region_lines(self)    496         lines =
self._get_sat_lines(kind='T',    497
  smin=self.smin,--> 498
smax=self.smax)    499         drawLines(self.fluid_ref, lines,
self.axis)    500
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Common.pyc
in _get_sat_lines(self, kind, smin, smax, num, x, line_opts)    161
         _, x_vals = self._get_fluid_data(self.graph_type[1],    162
                                           'Q', x,--> 163
                                kind, sat_mesh)    164     165
if self.graph_type[0] != kind:
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/Plots/Common.pyc
in _get_fluid_data(self, req_prop, prop1_name, prop1_vals, prop2_name,
prop2_vals)    129                                      prop1_name,
p1_val,    130                                      prop2_name,
prop2_vals[i],--> 131
self.fluid_ref))    132     133         return numpy.array([x_vals,
y_vals])
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/CoolProp.so
in CoolProp.CoolProp.PropsSI
(build/temp.macosx-10.5-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:12338)()
/Users/svance/anaconda/envs/py2k/lib/python2.7/site-packages/CoolProp/CoolProp.so
in CoolProp.CoolProp.PropsSI
(build/temp.macosx-10.5-x86_64-2.7/pyrex/CoolProp/CoolProp.cpp:11709)()
TypeError: only length-1 arrays can be converted to Python scalars

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Comment by ibell** [comment] 2014-07-23 03:31
Can you close this issue and open a new issue with the plotting?  We are
wandering off the topic from the first issue.

**Comment by vancesteven** [comment] 2014-07-23 03:44
okay.  thanks again for your help so far.

# 

Dr. Steve Vance
Astrobiologist, Planetary Scientist, Human
626-437-6200 (cell)

# vance.steven@gmail.com

**Closed as completed** 2014-07-28 06:41 UTC
