### ISSUE TITLE
h,s solver again

### ISSUE THREAD

**Issue by jowr** [ibell/coolprop#7] opened 2013-09-11 14:30 UTC
After installing the latest version, I experience problems with the h,s-solver. This point definitely worked earlier:

```
ValueError: Props failed ungracefully with inputs:"T",'H',1.6000000000000000e+02,'S',-1.5000000000000000e+00,"R600a";
ValueError: Props failed ungracefully with inputs:"T",'H',3.0000000000000000e+02,'S',-1.5000000000000000e+00,"R600a";
ValueError: Props failed ungracefully with inputs:"T",'H',1.6000000000000000e+02,'S',-0.3000000000000000e+00,"R600a";
```

It seem like there are some problems with the liquid and two-phase region, vapour seems to work. Can anyone verify this?

**Comment by ibell** [comment] 2013-09-14 22:00
I have seen other similar problems recently, I'm trying to determine the root cause

**Comment by ibell** [comment] 2013-09-15 20:38
Fixed at revision 147152f5f7d6796e54ce4ab8628b007f8d26f3f0 in the unitfied branch (soon to be merged back)

**Closed as completed by ibell** 2013-09-15 20:38 UTC
Labels: bug

**Comment by jowr** [comment] 2013-09-15 22:33
Great! What was wrong?

**Comment by ibell** [comment] 2013-09-16 06:34
I had not loaded the constants for the HS solver properly. The constants
are based on the CAS code rather than the fluid name (CAS code is stable,
will never change).  But for one section of code I was still trying to load
using the fluid name, which clearly failed.
